// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:android:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    storageBucket: 'reference-f2e84.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:web:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    authDomain: 'reference-f2e84.firebaseapp.com',
    storageBucket: 'reference-f2e84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:ios:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    storageBucket: 'reference-f2e84.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:ios:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    storageBucket: 'reference-f2e84.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:windows:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    storageBucket: 'reference-f2e84.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDfKKs0ZnTze16o2ASXgi0-rdm_q25kMnQ',
    appId: '1:1029834482024:linux:193b7f7f959747801ab6dd',
    messagingSenderId: '1029834482024',
    projectId: 'reference-f2e84',
    storageBucket: 'reference-f2e84.firebasestorage.app',
  );
}
